import 'package:icons_plus/icons_plus.dart';

class CategoryList {
  static const List<Map<String, dynamic>> categories = [
    // Income Categories
    {"title": "Salary", "icon": Iconsax.wallet_money_bold},
    {"title": "Investment Returns", "icon": Iconsax.chart_square_bold},
    {"title": "Rental Income", "icon": Iconsax.house_2_bold},
    {"title": "Dividends", "icon": Iconsax.chart_1_bold},
    {"title": "Interest Income", "icon": Iconsax.bank_outline},
    {"title": "Business Income", "icon": Iconsax.shop_bold},
    {"title": "Side Hustle", "icon": Iconsax.convert_3d_cube_bold},
    {"title": "Tax Refund", "icon": Iconsax.receipt_discount_bold},
    {"title": "Bonus", "icon": Iconsax.gift_bold},
    // Expense Categories
    {"title": "Food & Drinks", "icon": FontAwesome.burger_solid},
    {"title": "Groceries", "icon": FontAwesome.cart_shopping_solid},
    {"title": "Shopping", "icon": FontAwesome.bag_shopping_solid},
    {"title": "Rent", "icon": FontAwesome.house_solid},
    {"title": "Utilities", "icon": FontAwesome.bolt_solid},
    {"title": "Transportation", "icon": FontAwesome.car_solid},
    {"title": "Fuel", "icon": FontAwesome.gas_pump_solid},
    {"title": "Health", "icon": FontAwesome.heart_pulse_solid},
    {"title": "Insurance", "icon": FontAwesome.shield_halved_solid},
    {"title": "Education", "icon": FontAwesome.graduation_cap_solid},
    {"title": "Entertainment", "icon": FontAwesome.clapperboard_solid},
    {"title": "Travel", "icon": FontAwesome.plane_solid},
    {"title": "Savings", "icon": FontAwesome.piggy_bank_solid},
    {"title": "Investments", "icon": FontAwesome.chart_line_solid},
    {"title": "Loans", "icon": FontAwesome.hand_holding_dollar_solid},
    {"title": "Taxes", "icon": FontAwesome.money_check_dollar_solid},
    {"title": "Gifts & Donations", "icon": FontAwesome.gift_solid},
    {"title": "Pets", "icon": FontAwesome.dog_solid},
    {"title": "Clothing", "icon": FontAwesome.shirt_solid},
    {"title": "Subscriptions", "icon": FontAwesome.calendar_check_solid},
    {"title": "Phone & Internet", "icon": FontAwesome.phone_solid},
    {"title": "Electronics", "icon": FontAwesome.plug_solid},
    {"title": "Sports", "icon": FontAwesome.futbol_solid},
    {"title": "Hobbies", "icon": FontAwesome.palette_solid},
    {"title": "Self-Care", "icon": FontAwesome.spa_solid},
    {"title": "Kids", "icon": FontAwesome.child_solid},
    {"title": "Business", "icon": FontAwesome.briefcase_solid},
    {"title": "Legal", "icon": FontAwesome.scale_balanced_solid},
    {"title": "Household", "icon": FontAwesome.broom_solid},
    {"title": "Books", "icon": FontAwesome.book_solid},
    {"title": "Music", "icon": FontAwesome.music_solid},
    {"title": "Gaming", "icon": FontAwesome.gamepad_solid},
    {"title": "Streaming Services", "icon": FontAwesome.tv_solid},
    {
      "title": "Repair & Maintenance",
      "icon": FontAwesome.screwdriver_wrench_solid
    },
    {"title": "Charity", "icon": FontAwesome.hand_holding_heart_solid},
    {"title": "Events & Parties", "icon": FontAwesome.champagne_glasses_solid},
    {"title": "Freelancing", "icon": FontAwesome.laptop_solid},
    {"title": "Parking", "icon": FontAwesome.square_parking_solid},
    {"title": "Toll Fees", "icon": FontAwesome.road_solid},
    {"title": "Gym & Fitness", "icon": FontAwesome.dumbbell_solid},
    {"title": "Laundry", "icon": FontAwesome.jug_detergent_solid},
    {"title": "Babysitting", "icon": FontAwesome.baby_solid},
    {"title": "Cabs & Ride-Sharing", "icon": FontAwesome.taxi_solid},
    {"title": "Hotels & Stays", "icon": FontAwesome.hotel_solid},
    {"title": "Alcohol", "icon": FontAwesome.martini_glass_solid},
    {"title": "Cigarettes", "icon": FontAwesome.smoking_solid},
    {"title": "Beauty & Salon", "icon": FontAwesome.scissors_solid},
    {"title": "Work Lunch", "icon": FontAwesome.bowl_food_solid},
    {"title": "Miscellaneous", "icon": FontAwesome.ellipsis_solid},
  ];
}
